#!/bin/bash

#should I do this on startvnc?
vglclient &

#XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &

sleep 1

vglrun itksnap \
  -g $INPUT_DIR/ashs/tse.nii.gz \
  -s $INPUT_DIR/ashs/final/ashs_left_lfseg_corr_nogray.nii.gz \
  -l $INPUT_DIR/ashs/snaplabels.txt &

sleep 3600
